package com.pharmacare.report.util;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.time.LocalDate;

@Component
public class PdfGenerator {

    private static final Logger logger = LoggerFactory.getLogger(PdfGenerator.class);

    // ================= SALES =================

    public byte[] generateSalesPdf(double revenue,
                                   int transactions,
                                   double avg,
                                   String fromDate,
                                   String toDate) {

        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            Document document = new Document();
            PdfWriter.getInstance(document, out);

            document.open();

            // ================= FONTS =================
            Font companyFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Font labelFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
            Font valueFont = FontFactory.getFont(FontFactory.HELVETICA, 12);
            Font smallFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 9);

            // ================= COMPANY HEADER =================
            Paragraph company = new Paragraph("PHARMACARE MANAGEMENT SYSTEM", companyFont);
            company.setAlignment(Element.ALIGN_CENTER);
            document.add(company);

            Paragraph address = new Paragraph(
                    "COIMBATORE, Tamil Nadu | Contact: +91-9976218877",
                    FontFactory.getFont(FontFactory.HELVETICA, 13)
            );
            address.setAlignment(Element.ALIGN_CENTER);
            document.add(address);

            document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));

            // ================= TITLE =================
            Paragraph title = new Paragraph("SALES REPORT", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingBefore(10);
            title.setSpacingAfter(10);
            document.add(title);

            // ================= META =================
            document.add(new Paragraph("Report Period: " + fromDate + " to " + toDate,labelFont));
            document.add(new Paragraph("Generated On: " + LocalDate.now(), labelFont));
            document.add(new Paragraph(" "));

            document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
            document.add(new Paragraph(" "));

            // ================= TABLE =================
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10f);
            table.setSpacingAfter(10f);
            table.setWidths(new float[]{3, 2});

            addRow(table, "Total Revenue",
                    "₹ " + String.format("%.2f", revenue),
                    labelFont, valueFont);

            addRow(table, "Total Transactions",
                    String.valueOf(transactions),
                    labelFont, valueFont);

            addRow(table, "Average Ticket",
                    "₹ " + String.format("%.2f", avg),
                    labelFont, valueFont);

            document.add(table);

            document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));

            // ================= FOOTER =================
            Paragraph footer = new Paragraph(
                    "Confidential | Generated by Pharmacare System",
                    smallFont
            );
            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setSpacingBefore(20);
            document.add(footer);

            document.close();
            return out.toByteArray();

        } catch (Exception e) {
            logger.error("Error generating Sales PDF: ", e);
            throw new RuntimeException("Error generating professional sales PDF", e);
        }
    }

    // ================= PROFIT =================
    public byte[] generateProfitPdf(double profit) {

        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            Document document = new Document();
            PdfWriter.getInstance(document, out);

            document.open();

            // ================= FONTS =================
            Font companyFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Font labelFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
            Font valueFont = FontFactory.getFont(FontFactory.HELVETICA, 12);
            Font smallFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 9);

            // ================= COMPANY HEADER =================
            Paragraph company = new Paragraph("PHARMACARE MANAGEMENT SYSTEM", companyFont);
            company.setAlignment(Element.ALIGN_CENTER);
            document.add(company);

            Paragraph address = new Paragraph(
                    "COIMBATORE, Tamil Nadu | Contact: +91-9976218877",
                    FontFactory.getFont(FontFactory.HELVETICA, 13)
            );
            address.setAlignment(Element.ALIGN_CENTER);
            document.add(address);

            document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));

            // ================= TITLE =================
            Paragraph title = new Paragraph("PROFIT REPORT", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingBefore(10);
            title.setSpacingAfter(10);
            document.add(title);

            // ================= META =================
            document.add(new Paragraph("Generated On: " + LocalDate.now(), labelFont));
            document.add(new Paragraph(" "));

            document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
            document.add(new Paragraph(" "));

            // ================= TABLE =================
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10f);
            table.setSpacingAfter(10f);
            table.setWidths(new float[]{3, 2});

            addRow(table, "Estimated Profit",
                    "₹ " + String.format("%.2f", profit),
                    labelFont, valueFont);

            document.add(table);

            document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));

            // ================= FOOTER =================
            Paragraph footer = new Paragraph(
                    "Confidential | Generated by Pharmacare System",
                    smallFont
            );
            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setSpacingBefore(20);
            document.add(footer);

            document.close();
            return out.toByteArray();

        } catch (Exception e) {
            logger.error("Error generating Profit PDF: ", e);
            throw new RuntimeException("Error generating professional profit PDF", e);
        }
    }

    // ================= EXPIRY =================
    public byte[] generateExpiryPdf(int nearExpiryCount) {

        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            Document document = new Document();
            PdfWriter.getInstance(document, out);

            document.open();

            // ================= FONTS =================
            Font companyFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Font labelFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
            Font valueFont = FontFactory.getFont(FontFactory.HELVETICA, 12);
            Font smallFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 9);

            // ================= COMPANY HEADER =================
            Paragraph company = new Paragraph("PHARMACARE MANAGEMENT SYSTEM", companyFont);
            company.setAlignment(Element.ALIGN_CENTER);
            document.add(company);

            Paragraph address = new Paragraph(
                    "COIMBATORE, Tamil Nadu | Contact: +91-9976218877",
                    FontFactory.getFont(FontFactory.HELVETICA, 13)
            );
            address.setAlignment(Element.ALIGN_CENTER);
            document.add(address);

            document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));

            // ================= TITLE =================
            Paragraph title = new Paragraph("EXPIRY REPORT", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingBefore(10);
            title.setSpacingAfter(10);
            document.add(title);

            // ================= META =================
            document.add(new Paragraph("Generated On: " + LocalDate.now(), labelFont));
            document.add(new Paragraph(" "));

            document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
            document.add(new Paragraph(" "));

            // ================= TABLE =================
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10f);
            table.setSpacingAfter(10f);
            table.setWidths(new float[]{3, 2});

            addRow(table, "Near Expiry Medicines",
                    String.valueOf(nearExpiryCount),
                    labelFont, valueFont);

            document.add(table);

            document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));

            // ================= FOOTER =================
            Paragraph footer = new Paragraph(
                    "Confidential | Generated by Pharmacare System",
                    smallFont
            );
            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setSpacingBefore(20);
            document.add(footer);

            document.close();
            return out.toByteArray();

        } catch (Exception e) {
            logger.error("Error generating Expiry PDF: ", e);
            throw new RuntimeException("Error generating professional expiry PDF", e);
        }
    }
    // ================= TABLE HELPER =================
    private void addRow(PdfPTable table,
                        String label,
                        String value,
                        Font labelFont,
                        Font valueFont) {

        PdfPCell cell1 = new PdfPCell(new Paragraph(label, labelFont));
        cell1.setBorder(Rectangle.NO_BORDER);
        cell1.setPadding(8);

        PdfPCell cell2 = new PdfPCell(new Paragraph(value, valueFont));
        cell2.setHorizontalAlignment(Element.ALIGN_RIGHT);
        cell2.setBorder(Rectangle.NO_BORDER);
        cell2.setPadding(8);

        table.addCell(cell1);
        table.addCell(cell2);
    }
}